### ISSUE TITLE
求资源

### ISSUE THREAD

**Issue by ZhuangYuanL** [lipengzhou/nodejs-tutorial#2]
跪求李鹏周老师的视频教学资源~

**Comment by lengjuntao** [comment]
你是谁呀？




| |
邮箱：lengjuntaoyw@163.com
|

签名由 网易邮箱大师 定制

在2018年05月03日 16:11，ZhuangYuanL 写道：

跪求李鹏周老师的视频教学资源~

**Comment by ZhuangYuanL** [comment]
在网上看到李老师的视频,很喜欢李老师的授课方式,不过没能得到完整版

**Comment by lengjuntao** [comment]
我也没有呀……




| |
邮箱：lengjuntaoyw@163.com
|

签名由 网易邮箱大师 定制

在2018年05月03日 20:56，ZhuangYuanL 写道：

在网上看到李老师的视频,很喜欢李老师的授课方式,不过没能得到完整版

**Comment by ZhuangYuanL** [comment]
没有李老师带飞,自己跌跌撞撞学不到什么东西 :-(

**Comment by lipengzhou** [comment]
可以加我微信：lipengzhou9999，发资源。

**Comment by lipengzhou** [comment]
可以给邮件联系：lpzmail@163.com
